apiVersion: v1
kind: ConfigMap
metadata:
  name: trendtrove-config
data:
  NODE_ENV: production
  APP_DOMAIN: http://your-domain.local
  GOOGLE_CALLBACK_URL: http://your-domain.local/auth/google/callback
  SESSION_COOKIE_SECURE: "false"
  SESSION_COOKIE_DOMAIN: your-domain.local
  SESSION_COOKIE_SAME_SITE: lax
