apiVersion: v1
kind: ConfigMap
metadata:
  name: trendtrove-config
data:
  NODE_ENV: development
  APP_DOMAIN: http://127.0.0.1.nip.io
  GOOGLE_CALLBACK_URL: http://127.0.0.1.nip.io/auth/google/callback
  SESSION_COOKIE_SECURE: "false"
  SESSION_COOKIE_DOMAIN: 127.0.0.1.nip.io
  SESSION_COOKIE_SAME_SITE: lax
