apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trendtrove-app
  namespace: ecommerce
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trendtrove-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trendtrove-app-v2
  namespace: ecommerce
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trendtrove-app-v2
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trendtrove-auth
  namespace: ecommerce
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trendtrove-auth
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trendtrove-product
  namespace: ecommerce
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: product-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trendtrove-cart
  namespace: ecommerce
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cart-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trendtrove-mail
  namespace: ecommerce
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mail-service
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
